name: "Release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Create ZIP"
        run: |
          zip -r forsyningonline.zip custom_components/

      - name: "Create Release"
        uses: "softprops/action-gh-release@v1"
        with:
          files: "forsyningonline.zip"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
